/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './angular2-social-login.module';
import * as i2 from './auth.service';
export const Angular2SocialLoginModuleNgFactory:i0.NgModuleFactory<i1.Angular2SocialLoginModule> = i0.ɵcmf(i1.Angular2SocialLoginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AuthService,i2.AuthService,([] as any[])),i0.ɵmpd(512,i1.Angular2SocialLoginModule,
          i1.Angular2SocialLoginModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFub2VsX21vdG9zby9QUk9KRVRPUy9ucG0tbW9kdWxlcy9hbmd1bGFyMi1zb2NpYWwtYXV0aC9zcmMvYW5ndWxhcjItc29jaWFsLWxvZ2luLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL21hbm9lbF9tb3Rvc28vUFJPSkVUT1MvbnBtLW1vZHVsZXMvYW5ndWxhcjItc29jaWFsLWF1dGgvc3JjL2FuZ3VsYXIyLXNvY2lhbC1sb2dpbi5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
