/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './angular2-social-login.module';
import * as i2 from './auth.service';
export const Angular2SocialLoginModuleNgFactory:i0.NgModuleFactory<i1.Angular2SocialLoginModule> = i0.ɵcmf(i1.Angular2SocialLoginModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AuthService,i2.AuthService,([] as any[])),i0.ɵmpd(512,i1.Angular2SocialLoginModule,
          i1.Angular2SocialLoginModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFub2VsX21vdG9zby9QUk9KRVRPUy9ucG0tbW9kdWxlcy9hbmd1bGFyMi1zb2NpYWwtbG9naW4vc3JjL2FuZ3VsYXIyLXNvY2lhbC1sb2dpbi5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9tYW5vZWxfbW90b3NvL1BST0pFVE9TL25wbS1tb2R1bGVzL2FuZ3VsYXIyLXNvY2lhbC1sb2dpbi9zcmMvYW5ndWxhcjItc29jaWFsLWxvZ2luLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
